package workbench

import (
	"fmt"
	"strings"

	"github.com/abc-cluster/abc-cluster-cli/internal/config"
	wbinternal "github.com/abc-cluster/abc-cluster-cli/internal/workbench"
	"github.com/spf13/cobra"
)

// defaultAtuinVersion is the pinned atuin release installed when atuin is absent.
// Use the musl static binary — works on any Linux x86_64 without libc deps.
const defaultAtuinVersion = "v18.4.0"

// atuinBashrcMarker is the line we check for before adding the init stanza —
// prevents duplicate entries on re-run.
const atuinBashrcMarker = "# atuin — abc-workbench"

// atuinBashrcStanza is appended to each slot's .bashrc once.
const atuinBashrcStanza = `
# atuin — abc-workbench shell history (local-only, no sync)
if command -v atuin &>/dev/null; then
    eval "$(atuin init bash --disable-up-arrow)"
fi
`

// atuinConfigTOML is written to ~/.config/atuin/config.toml for each slot.
// local-only: no server, no sync, no keys needed.
const atuinConfigTOML = `# abc-workbench atuin config — generated by abc admin services workbench provision-atuin
# local-only: history is stored in this slot's home dir only.
[sync]
auto_sync = false
sync_address = ""

[history]
ignore_failure = true
`

func newProvisionAtuinCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "provision-atuin",
		Short: "Seed atuin into slot home dirs so JupyterLab terminals get persistent history",
		Long: `Install atuin system-wide on the platform node (if not already present) and
configure it for every workbench slot so that opening a terminal in JupyterLab
automatically gives the user persistent, searchable shell history (Ctrl+R).

Each slot gets:
  ~/.bashrc         — eval "$(atuin init bash)" stanza (idempotent)
  ~/.config/atuin/config.toml — local-only config (no sync server, no keys)

History is stored in the slot's own home dir at:
  /data/workbench/<slot>/home/.local/share/atuin/history.db

Because the home dir persists between JupyterHub server stops and starts,
history accumulates across sessions automatically.

Examples:

  # Provision all slots:
  abc admin services workbench provision-atuin

  # Provision specific slots only:
  abc admin services workbench provision-atuin --slots calm-dassie,lunar-hornbill

  # Dry-run: show what would be done without changing anything:
  abc admin services workbench provision-atuin --dry-run`,
		RunE: runProvisionAtuin,
	}

	cmd.Flags().String("node", "", "SSH host alias for the platform node (default: sun-<node> from config or sun-aither)")
	cmd.Flags().String("slots", "", "Comma-separated slot names to provision (default: all slots discovered under /data/workbench/)")
	cmd.Flags().String("atuin-version", defaultAtuinVersion, "atuin release tag to install if atuin is not already present")
	cmd.Flags().Bool("dry-run", false, "Print what would be done without modifying anything")

	return cmd
}

func runProvisionAtuin(cmd *cobra.Command, args []string) error {
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	actx := cfg.ActiveCtx()

	nodeOverride, _ := cmd.Flags().GetString("node")
	slotsFlag, _ := cmd.Flags().GetString("slots")
	atuinVersion, _ := cmd.Flags().GetString("atuin-version")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	node := nodeFromCtx(actx, nodeOverride)

	if dryRun {
		fmt.Fprintln(cmd.ErrOrStderr(), "[dry-run] No changes will be made.")
	}

	// --- 1. Ensure atuin is installed system-wide ---
	if err := ensureAtuinInstalled(cmd, node, atuinVersion, dryRun); err != nil {
		return err
	}

	// --- 2. Discover or parse slot list ---
	slots, err := resolveSlots(node, slotsFlag)
	if err != nil {
		return fmt.Errorf("resolve slots: %w", err)
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "Provisioning atuin for %d slot(s)...\n", len(slots))

	// --- 3. Seed each slot ---
	ok, skipped, failed := 0, 0, 0
	for _, slot := range slots {
		homeDir := "/data/workbench/" + slot + "/home"
		if err := provisionSlot(cmd, node, slot, homeDir, dryRun); err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "  [%s] error: %v\n", slot, err)
			failed++
		} else {
			ok++
		}
		_ = skipped
	}

	fmt.Fprintf(cmd.OutOrStdout(),
		"Done: %d provisioned, %d failed.\n", ok, failed,
	)
	if failed > 0 {
		return fmt.Errorf("%d slot(s) failed", failed)
	}
	return nil
}

// ensureAtuinInstalled checks if atuin is at /usr/local/bin/atuin on node.
// If not, downloads and installs the pinned musl static binary.
func ensureAtuinInstalled(cmd *cobra.Command, node wbinternal.NodeSSH, version string, dryRun bool) error {
	out, _ := wbinternal.RunOnNodePublic(node, "test", "-x", "/usr/local/bin/atuin", "&&", "echo", "present")
	if strings.Contains(out, "present") {
		v, _ := wbinternal.RunOnNodePublic(node, "/usr/local/bin/atuin", "--version")
		fmt.Fprintf(cmd.OutOrStdout(), "atuin already installed: %s\n", strings.TrimSpace(v))
		return nil
	}

	tarball := fmt.Sprintf(
		"https://github.com/atuinsh/atuin/releases/download/%s/atuin-%s-x86_64-unknown-linux-musl.tar.gz",
		version, version,
	)
	fmt.Fprintf(cmd.OutOrStdout(), "Installing atuin %s on %s...\n", version, node.Host)

	if dryRun {
		fmt.Fprintf(cmd.OutOrStdout(), "  [dry-run] would download %s → /usr/local/bin/atuin\n", tarball)
		return nil
	}

	script := fmt.Sprintf(`set -euo pipefail
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
curl -fsSL %q | tar xz -C "$TMP" --wildcards '*/atuin' --strip-components=1
sudo mv "$TMP/atuin" /usr/local/bin/atuin
sudo chmod 755 /usr/local/bin/atuin
atuin --version
`, tarball)

	out, err := wbinternal.RunScriptOnNodePublic(node, script, false)
	if err != nil {
		return fmt.Errorf("install atuin on %s: %w\n%s", node.Host, err, out)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "  installed: %s\n", strings.TrimSpace(out))
	return nil
}

// resolveSlots returns the slot list from the flag or by listing /data/workbench/.
func resolveSlots(node wbinternal.NodeSSH, slotsFlag string) ([]string, error) {
	if slotsFlag != "" {
		var out []string
		for _, s := range strings.Split(slotsFlag, ",") {
			s = strings.TrimSpace(s)
			if s != "" {
				out = append(out, s)
			}
		}
		return out, nil
	}

	// Discover all slot home dirs: /data/workbench/<slot>/home must exist.
	// Passed as a single SSH argument so the remote shell receives it verbatim
	// (no bash -c wrapping, which SSH arg-joining would corrupt).
	raw, err := wbinternal.RunOnNodePublic(node,
		`find /data/workbench -mindepth 2 -maxdepth 2 -name home -type d -printf '%P\n' 2>/dev/null | sed 's|/home||' | sort`,
	)
	if err != nil {
		return nil, fmt.Errorf("list slots on %s: %w\n%s", node.Host, err, raw)
	}

	var slots []string
	for _, line := range strings.Split(strings.TrimSpace(raw), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			slots = append(slots, line)
		}
	}
	if len(slots) == 0 {
		return nil, fmt.Errorf("no slot home dirs found under /data/workbench/ on %s", node.Host)
	}
	return slots, nil
}

// provisionSlot seeds atuin config and .bashrc for one slot.
// homeDir is the slot's home dir on the node (e.g. /data/workbench/calm-dassie/home).
// Idempotent: checks for the marker before appending .bashrc; overwrites config.toml.
func provisionSlot(cmd *cobra.Command, node wbinternal.NodeSSH, slot, homeDir string, dryRun bool) error {
	if dryRun {
		fmt.Fprintf(cmd.OutOrStdout(), "  [dry-run] %s: would seed .bashrc + config.toml\n", slot)
		return nil
	}

	script := fmt.Sprintf(`set -euo pipefail
HOME_DIR=%q
BASHRC="$HOME_DIR/.bashrc"
CONFIG_DIR="$HOME_DIR/.config/atuin"
CONFIG_FILE="$CONFIG_DIR/config.toml"
MARKER=%q
STANZA=%q
TOML=%q

# .bashrc: create if absent, append stanza only if marker not present
touch "$BASHRC"
if ! grep -qF "$MARKER" "$BASHRC"; then
    printf '%%s' "$STANZA" >> "$BASHRC"
fi

# atuin config.toml: always write (idempotent content)
mkdir -p "$CONFIG_DIR"
printf '%%s' "$TOML" > "$CONFIG_FILE"

echo "ok"
`,
		homeDir,
		atuinBashrcMarker,
		atuinBashrcStanza,
		atuinConfigTOML,
	)

	out, err := wbinternal.RunScriptOnNodePublic(node, script, false)
	if err != nil {
		return fmt.Errorf("%w\n%s", err, out)
	}
	if !strings.Contains(out, "ok") {
		return fmt.Errorf("unexpected output: %s", out)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "  %s: ok\n", slot)
	return nil
}
