# HashiCorp Boundary Controller — configuration reference
#
# This file documents the controller config layout.
# The DEPLOYED file (/etc/boundary.d/controller.hcl) is generated by
# deploy-boundary-controller.sh with KMS keys and DB credentials substituted
# inline at deploy time (same pattern as deploy-consul.sh generates consul.hcl).
#
# Secrets come from acl/boundary-controller.env (generated by bootstrap-secrets.sh).
# The deployed config is chmod 640 boundary:boundary on the server.
#
# Ports
# ─────
#   9200 — API / UI (Traefik → boundary.aither)
#   9201 — cluster  (workers connect here via Consul DNS)
#   9202 — proxy    (data plane, legacy listener)

disable_mlock = true

controller {
  name        = "abc-nodes-boundary-controller"
  description = "abc-nodes Boundary controller — manages SSH session brokering"

  database {
    # Connection string substituted by deploy-boundary-controller.sh
    url = "postgresql://<DB_USER>:<DB_PASSWORD>@<DB_HOST>:<DB_PORT>/<DB_NAME>?sslmode=disable"
  }
}

listener "tcp" {
  address     = "0.0.0.0:9200"
  purpose     = "api"
  tls_disable = true
}

listener "tcp" {
  address     = "0.0.0.0:9201"
  purpose     = "cluster"
  tls_disable = true
}

listener "tcp" {
  address     = "0.0.0.0:9202"
  purpose     = "proxy"
  tls_disable = true
}

# Root KMS — encrypts Boundary's internal root key hierarchy.
# Key value substituted by deploy-boundary-controller.sh from BOUNDARY_ROOT_KEY.
kms "aead" {
  purpose   = "root"
  aead_type = "aes-gcm"
  key       = "<BOUNDARY_ROOT_KEY>"
  key_id    = "global_root"
}

# Worker-auth KMS — authenticates workers to this controller.
# Must match the key used in boundary-worker.nomad.hcl (BOUNDARY_WORKER_AUTH_KEY).
kms "aead" {
  purpose   = "worker-auth"
  aead_type = "aes-gcm"
  key       = "<BOUNDARY_WORKER_AUTH_KEY>"
  key_id    = "global_worker_auth"
}

# Recovery KMS — used for emergency access if root KMS is unavailable.
kms "aead" {
  purpose   = "recovery"
  aead_type = "aes-gcm"
  key       = "<BOUNDARY_RECOVERY_KEY>"
  key_id    = "global_recovery"
}
