# Traefik reverse proxy — abc-nodes floor
# Uses raw_exec so the process runs directly on the host with full network access.
# This allows it to bind to privileged ports and reach backend services at
# 127.0.0.1:PORT (registered by bridge-mode Nomad allocations via CNI).
#
# Dynamic routes are generated by Nomad's template engine (which runs on the
# host and has Nomad API access) — no Nomad provider connection needed.
#
# Ports: 8081 (HTTP entry), 8888 (Traefik dashboard)

variable "datacenters" {
  type    = list(string)
  default = ["dc1", "default"]
}

variable "traefik_version" {
  type    = string
  default = "3.3.5"
}

job "abc-nodes-traefik" {
  namespace = "abc-services"
  region      = "global"
  datacenters = var.datacenters
  type        = "service"

  meta {
    abc_cluster_type = "abc-nodes"
    service          = "traefik"
  }

  group "traefik" {
    count = 1

    network {
      mode = "host"
      port "http" {
        static = 8081
      }
      port "dashboard" {
        static = 8888
      }
    }

    task "traefik" {
      driver = "raw_exec"

      config {
        command = "local/traefik"
        args    = ["--configFile=local/traefik.yml"]
      }

      artifact {
        source      = "https://github.com/traefik/traefik/releases/download/v${var.traefik_version}/traefik_v${var.traefik_version}_linux_amd64.tar.gz"
        destination = "local/"
      }

      # Static Traefik configuration.
      template {
        data        = <<EOF
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

# Enables /ping on the traefik entry point for `traefik healthcheck` (e.g. abc config sync).
ping: {}

entryPoints:
  web:
    address: ":8081"
  traefik:
    address: ":8888"

providers:
  file:
    filename: local/routes.yml
    watch: true

log:
  level: INFO
EOF
        destination = "local/traefik.yml"
      }

      # Dynamic routes — regenerated by Nomad template engine whenever
      # a registered service address changes.
      # Includes ForwardAuth middleware (nomad-auth) wired to abc-nodes-auth
      # sidecar on :9191. tusd requires a valid Nomad ACL token to upload.
      template {
        change_mode = "noop"
        data        = <<EOF
http:
  middlewares:
    # ForwardAuth: validates X-Nomad-Token / Authorization: Bearer headers
    # by calling the abc-nodes-auth sidecar. See acl/traefik/traefik-nomad-auth.yml
    # for documentation. Propagated headers appear in tusd access logs.
    nomad-auth:
      forwardAuth:
        address: "http://127.0.0.1:9191/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User"
          - "X-Auth-Group"
          - "X-Auth-Namespace"

  routers:
    grafana:
      entryPoints: ["web"]
      rule: "Host(`grafana.aither`)"
      service: grafana
    grafana-alloy:
      entryPoints: ["web"]
      rule: "Host(`grafana-alloy.aither`)"
      service: grafana-alloy
    loki:
      entryPoints: ["web"]
      rule: "Host(`loki.aither`)"
      service: loki
    minio-s3:
      entryPoints: ["web"]
      rule: "Host(`minio.aither`)"
      service: minio-s3
    minio-console:
      entryPoints: ["web"]
      rule: "Host(`minio-console.aither`)"
      service: minio-console
    ntfy:
      entryPoints: ["web"]
      rule: "Host(`ntfy.aither`)"
      service: ntfy
    prometheus:
      entryPoints: ["web"]
      rule: "Host(`prometheus.aither`)"
      service: prometheus
    rustfs:
      entryPoints: ["web"]
      rule: "Host(`rustfs.aither`)"
      service: rustfs
    tusd:
      entryPoints: ["web"]
      rule: "Host(`tusd.aither`)"
      middlewares:
        - nomad-auth
      service: tusd
    vault:
      entryPoints: ["web"]
      rule: "Host(`vault.aither`)"
      service: vault
    uppy:
      entryPoints: ["web"]
      rule: "Host(`uppy.aither`)"
      service: uppy
    wave:
      entryPoints: ["web"]
      rule: "Host(`wave.aither`)"
      service: wave
    faasd:
      entryPoints: ["web"]
      rule: "Host(`faasd.aither`)"
      service: faasd
    supabase:
      entryPoints: ["web"]
      rule: "Host(`supabase.aither`)"
      service: supabase
    supabase-studio:
      entryPoints: ["web"]
      rule: "Host(`supabase-studio.aither`)"
      service: supabase-studio

  services:
    # abc-nodes floor uses static host ports for each service.
    # Keep static backends here so Traefik routing does not depend on Nomad
    # template ACL capabilities to query the service catalog.
    grafana:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
    grafana-alloy:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:12345"
    loki:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3100"
    minio-s3:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9000"
    minio-console:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9001"
    ntfy:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8088"
    prometheus:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9090"
    rustfs:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9900"
    tusd:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
    vault:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8200"
    uppy:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8085"
    wave:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9091"
    faasd:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8089"
    supabase:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8000"
    supabase-studio:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3002"
EOF
        destination = "local/routes.yml"
      }

      resources {
        cpu    = 256
        memory = 256
      }

      service {
        name     = "abc-nodes-traefik"
        port     = "http"
        provider = "nomad"
        tags     = ["abc-nodes", "traefik", "proxy"]
      }

      service {
        name     = "abc-nodes-traefik-dashboard"
        port     = "dashboard"
        provider = "nomad"
        tags     = ["abc-nodes", "traefik", "dashboard"]
      }
    }
  }
}
