# Traefik reverse proxy — abc-nodes floor
# Uses raw_exec so the process runs directly on the host with full network access.
# This allows it to bind to privileged ports and reach backend services at
# 127.0.0.1:PORT (registered by bridge-mode Nomad allocations via CNI).
#
# Dynamic routes are generated by Nomad's template engine (which runs on the
# host and has Nomad API access) — no Nomad provider connection needed.
#
# Ports: 80 (HTTP entry), 8888 (Traefik dashboard)

variable "datacenters" {
  type    = list(string)
  default = ["dc1", "default"]
}

variable "traefik_version" {
  type    = string
  default = "3.3.5"
}

job "abc-nodes-traefik" {
  namespace = "services"
  region      = "global"
  datacenters = var.datacenters
  type        = "service"

  meta {
    abc_cluster_type = "abc-nodes"
    service          = "traefik"
  }

  group "traefik" {
    count = 1

    network {
      mode = "host"
      port "http" {
        static = 80
      }
      port "dashboard" {
        static = 8888
      }
    }

    task "traefik" {
      driver = "raw_exec"

      config {
        command = "local/traefik"
        args    = ["--configFile=local/traefik.yml"]
      }

      artifact {
        source      = "https://github.com/traefik/traefik/releases/download/v${var.traefik_version}/traefik_v${var.traefik_version}_linux_amd64.tar.gz"
        destination = "local/"
      }

      # Static Traefik configuration.
      template {
        data        = <<EOF
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

# Enables /ping on the traefik entry point for `traefik healthcheck` (e.g. abc config sync).
ping: {}

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8888"

providers:
  file:
    filename: local/routes.yml
    watch: true

log:
  level: INFO
EOF
        destination = "local/traefik.yml"
      }

      # Dynamic routes — regenerated by Nomad template engine whenever
      # a registered service address changes.
      template {
        change_mode = "noop"
        data        = <<EOF
http:
  routers:
    grafana:
      entryPoints: ["web"]
      rule: "Host(`grafana.aither`)"
      service: grafana
    grafana-alloy:
      entryPoints: ["web"]
      rule: "Host(`grafana-alloy.aither`)"
      service: grafana-alloy
    loki:
      entryPoints: ["web"]
      rule: "Host(`loki.aither`)"
      service: loki
    minio-s3:
      entryPoints: ["web"]
      rule: "Host(`minio.aither`)"
      service: minio-s3
    minio-console:
      entryPoints: ["web"]
      rule: "Host(`minio-console.aither`)"
      service: minio-console
    ntfy:
      entryPoints: ["web"]
      rule: "Host(`ntfy.aither`)"
      service: ntfy
    prometheus:
      entryPoints: ["web"]
      rule: "Host(`prometheus.aither`)"
      service: prometheus
    rustfs:
      entryPoints: ["web"]
      rule: "Host(`rustfs.aither`)"
      service: rustfs
    tusd:
      entryPoints: ["web"]
      rule: "Host(`tusd.aither`)"
      service: tusd
    vault:
      entryPoints: ["web"]
      rule: "Host(`vault.aither`)"
      service: vault
    uppy:
      entryPoints: ["web"]
      rule: "Host(`uppy.aither`)"
      service: uppy

  services:
    grafana:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-grafana" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    grafana-alloy:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-alloy" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    loki:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-loki" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    minio-s3:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-minio-s3" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    minio-console:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-minio-console" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    ntfy:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-ntfy" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    prometheus:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-prometheus" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    rustfs:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-rustfs-s3" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    tusd:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-tusd" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    vault:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-vault" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
    uppy:
      loadBalancer:
        servers:{{ range nomadService "abc-nodes-uppy" }}
          - url: "http://{{ .Address }}:{{ .Port }}"{{ end }}
EOF
        destination = "local/routes.yml"
      }

      resources {
        cpu    = 256
        memory = 256
      }

      service {
        name     = "abc-nodes-traefik"
        port     = "http"
        provider = "nomad"
        tags     = ["abc-nodes", "traefik", "proxy"]
      }

      service {
        name     = "abc-nodes-traefik-dashboard"
        port     = "dashboard"
        provider = "nomad"
        tags     = ["abc-nodes", "traefik", "dashboard"]
      }
    }
  }
}
