package appgen

// scaffold.go — generators for `abc app init`: a pre-filled abc-app.yaml and an
// optional framework-appropriate Dockerfile starter. Pure string generation, no
// I/O — the command layer owns file writing + overwrite refusal.

import (
	"fmt"
	"sort"
	"strings"
)

// ScaffoldOptions carries the resolved inputs for init's file generation.
type ScaffoldOptions struct {
	Framework string // streamlit | shiny | pode | custom (normalised, lowercase)
	Name      string // app name; "" → a framework-flavoured placeholder
	Project   string // project/group; "" → a placeholder
}

// ScaffoldPort returns the resolved default port for the scaffold's framework.
// custom (which has no table default) falls back to 8080 as a starter value.
func (o ScaffoldOptions) ScaffoldPort() int {
	if def, ok := frameworkDefaults[o.Framework]; ok && def.port != 0 {
		return def.port
	}
	return 8080
}

// ScaffoldHealth returns the resolved default health path for the scaffold's
// framework. custom falls back to "/".
func (o ScaffoldOptions) ScaffoldHealth() string {
	if def, ok := frameworkDefaults[o.Framework]; ok && def.health != "" {
		return def.health
	}
	return "/"
}

func (o ScaffoldOptions) scaffoldName() string {
	if strings.TrimSpace(o.Name) != "" {
		return strings.TrimSpace(o.Name)
	}
	return "my-" + o.Framework + "-app"
}

func (o ScaffoldOptions) scaffoldProject() string {
	if strings.TrimSpace(o.Project) != "" {
		return strings.TrimSpace(o.Project)
	}
	return "my-project"
}

// ScaffoldYAML renders a pre-filled abc-app.yaml. Required fields (name, image,
// project, framework) are set; port/health carry the framework defaults as
// explicit values so the file is self-documenting; data/env/resources are shown
// as commented blocks the researcher can uncomment.
func ScaffoldYAML(o ScaffoldOptions) string {
	name := o.scaffoldName()
	project := o.scaffoldProject()
	port := o.ScaffoldPort()
	health := o.ScaffoldHealth()

	var b strings.Builder
	b.WriteString("# abc-app.yaml — scientific app descriptor (`abc app deploy`)\n")
	b.WriteString("# Generated by `abc app init`. Edit the values, then `abc app validate`.\n")
	b.WriteString("\n")
	b.WriteString("version: \"" + CurrentSpecVersion + "\"   # abc-app.yaml schema version (kept first, like config.yaml)\n")
	b.WriteString("name: " + name + "\n")
	b.WriteString("project: " + project + "          # the group you deploy as (access: team is scoped to it)\n")
	b.WriteString("framework: " + o.Framework + "\n")
	b.WriteString("\n")
	b.WriteString("# A fully-qualified, pre-built OCI image. There is no source-based build\n")
	b.WriteString("# path: build + push the image yourself, then reference it here.\n")
	b.WriteString("image: ghcr.io/your-org/" + name + ":latest\n")
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("port: %d            # container listen port (must bind 0.0.0.0)\n", port))
	b.WriteString("health: " + health + "      # HTTP path Nomad polls for readiness\n")
	b.WriteString("\n")
	b.WriteString("access: team        # phase 1: team only (cluster/public are reserved)\n")
	b.WriteString("exposure: public    # network reach: public (default) | internal | both\n")
	b.WriteString("                    #   internal = institution-only (Tailscale + campus LAN, off the public edge)\n")
	b.WriteString("\n")
	b.WriteString("# resources:        # hard Nomad limits (defaults: cpu 500 MHz, memory 1024 MiB)\n")
	b.WriteString("#   cpu: 500        # MHz\n")
	b.WriteString("#   memory: 1024    # MiB\n")
	b.WriteString("\n")
	b.WriteString("# env:              # plain (non-secret) env vars injected into the container.\n")
	b.WriteString("#   LOG_LEVEL: info # ABC_*/AWS_* are platform-injected and cannot be set here.\n")
	b.WriteString("\n")
	b.WriteString("# data:             # MinIO buckets the app reads/writes (Vault-minted AWS_* creds).\n")
	b.WriteString("#   - bucket: my-bucket\n")
	b.WriteString("#     access: read  # read (default) or read-write\n")
	return b.String()
}

// ScaffoldDockerfile renders a minimal, framework-appropriate Dockerfile starter
// that honours the container bind contract: listen on 0.0.0.0 at the declared
// port with the framework's run command. The image is intentionally a starting
// point — the researcher fills in their app source + dependencies.
func ScaffoldDockerfile(o ScaffoldOptions) string {
	port := o.ScaffoldPort()
	switch o.Framework {
	case "streamlit":
		return strings.Join([]string{
			"# Streamlit app — minimal starter (abc app init --with-dockerfile)",
			"FROM python:3.12-slim",
			"WORKDIR /app",
			"COPY requirements.txt ./",
			"RUN pip install --no-cache-dir -r requirements.txt",
			"COPY . .",
			fmt.Sprintf("EXPOSE %d", port),
			"# Bind contract: 0.0.0.0 + the declared port; headless disables the",
			"# first-run prompt and browser-open that otherwise hang a container.",
			fmt.Sprintf("CMD [\"streamlit\", \"run\", \"app.py\", \"--server.address=0.0.0.0\", \"--server.port=%d\", \"--server.headless=true\", \"--server.enableCORS=false\", \"--server.enableXsrfProtection=false\"]", port),
			"",
		}, "\n")
	case "shiny":
		return strings.Join([]string{
			"# R Shiny app — minimal starter (abc app init --with-dockerfile)",
			"FROM rocker/shiny:latest",
			"WORKDIR /srv/shiny-server/app",
			"COPY . .",
			fmt.Sprintf("EXPOSE %d", port),
			"# Bind contract: standalone Shiny defaults to 127.0.0.1 + a random port,",
			"# so host/port MUST be pinned to 0.0.0.0:<port> or Traefik can't reach it.",
			fmt.Sprintf("CMD [\"R\", \"-e\", \"options(shiny.host='0.0.0.0', shiny.port=%d); shiny::runApp('.')\"]", port),
			"",
		}, "\n")
	case "pode":
		return strings.Join([]string{
			"# Pode/Pode.Web app — minimal starter (abc app init --with-dockerfile)",
			"FROM mcr.microsoft.com/powershell:latest",
			"WORKDIR /app",
			"RUN pwsh -c \"Install-Module -Name Pode -Force -Scope AllUsers\"",
			"COPY . .",
			fmt.Sprintf("EXPOSE %d", port),
			"# Bind contract: bind 0.0.0.0:<port> in your server.ps1, e.g.",
			fmt.Sprintf("#   Add-PodeEndpoint -Address 0.0.0.0 -Port %d -Protocol Http", port),
			fmt.Sprintf("ENV PODE_HOST=0.0.0.0 PODE_PORT=%d", port),
			"CMD [\"pwsh\", \"./server.ps1\"]",
			"",
		}, "\n")
	default: // custom and any other value
		return strings.Join([]string{
			"# Custom app — minimal starter (abc app init --with-dockerfile)",
			"# Replace the base image + run command with your framework's.",
			"FROM debian:stable-slim",
			"WORKDIR /app",
			"COPY . .",
			fmt.Sprintf("EXPOSE %d", port),
			fmt.Sprintf("# Bind contract: your process MUST listen on 0.0.0.0:%d (not localhost).", port),
			"CMD [\"./run.sh\"]",
			"",
		}, "\n")
	}
}

// ── Protected platform-injected env vars ────────────────────────────────────

// protectedEnvExact is the set of platform-injected env keys that researchers
// may never set or unset via `abc app config`. They are owned by the platform's
// env-injection contract (see platformEnv in hclgen.go).
var protectedEnvExact = map[string]bool{
	"AWS_ACCESS_KEY_ID":     true,
	"AWS_SECRET_ACCESS_KEY": true,
	"ABC_MINIO_ENDPOINT":    true,
}

// IsProtectedEnvKey reports whether key is a platform-injected variable that
// `abc app config set/unset` must refuse to touch. Any ABC_* or AWS_* key is
// protected, plus the explicit endpoint key (covered by the ABC_ prefix too,
// but listed for clarity).
func IsProtectedEnvKey(key string) bool {
	k := strings.ToUpper(strings.TrimSpace(key))
	if protectedEnvExact[k] {
		return true
	}
	return strings.HasPrefix(k, "ABC_") || strings.HasPrefix(k, "AWS_")
}

// PlatformEnvKeys returns the sorted set of platform-injected env keys (the keys
// `config list` redacts and `config get` refuses to surface raw). Derived from
// the same platformEnv contract the generator emits.
func PlatformEnvKeys() []string {
	keys := []string{
		"ABC_APP_NAME", "ABC_APP_URL", "ABC_APP_BASE_URL", "ABC_PROJECT",
		"ABC_MINIO_ENDPOINT", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY",
	}
	sort.Strings(keys)
	return keys
}

// ResolvedSummary returns a human-readable listing of the spec's resolved
// (post-Validate + ApplyDefaults) values, for `abc app validate`. It does not
// contact the cluster — it reflects only what the descriptor + defaults imply.
func (s *Spec) ResolvedSummary() string {
	var b strings.Builder
	fmt.Fprintf(&b, "  version     %s\n", normalizeSpecVersion(s.Version))
	fmt.Fprintf(&b, "  name        %s\n", s.Name)
	fmt.Fprintf(&b, "  project     %s\n", s.Project)
	fmt.Fprintf(&b, "  framework   %s\n", s.NormFramework())
	fmt.Fprintf(&b, "  image       %s\n", s.Image)
	fmt.Fprintf(&b, "  port        %d\n", s.Port)
	fmt.Fprintf(&b, "  health      %s\n", s.Health)
	fmt.Fprintf(&b, "  access      %s\n", s.Access)
	fmt.Fprintf(&b, "  exposure    %s\n", s.NormExposure())
	fmt.Fprintf(&b, "  replicas    %d\n", s.Replicas)
	fmt.Fprintf(&b, "  resources   cpu=%dMHz memory=%dMiB\n", s.Resources.CPU, s.Resources.Memory)
	fmt.Fprintf(&b, "  job         %s (namespace %s)\n", s.JobName(), DefaultNamespace)
	fmt.Fprintf(&b, "  url         %s\n", s.URL())
	if len(s.Env) > 0 {
		fmt.Fprintf(&b, "  env\n")
		for _, k := range sortedKeys(s.Env) {
			fmt.Fprintf(&b, "    %s=%s\n", k, s.Env[k])
		}
	}
	if len(s.Data) > 0 {
		fmt.Fprintf(&b, "  data\n")
		for _, d := range s.Data {
			acc := d.Access
			if acc == "" {
				acc = AccessRead
			}
			fmt.Fprintf(&b, "    %s (%s)\n", d.Bucket, acc)
		}
	}
	return b.String()
}
