package workbench

import (
	"crypto/sha256"
	"fmt"
)

// DeriveToken produces a stable 16-char hex workbench password from the user's
// MinIO secret key. Same key → same password every session. If secretKey is
// empty (e.g. operator-configured cluster), a random token should be used instead.
func DeriveToken(secretKey string) string {
	h := sha256.Sum256([]byte(secretKey))
	return fmt.Sprintf("%x", h[:8]) // 16 hex chars
}

// ideImages maps IDE name → default container image.
// quarto uses abc-quarto-base (in-house image, built separately).
// code-server uses the upstream codercom image (usable immediately for testing).
var ideImages = map[string]string{
	"quarto":      "ghcr.io/abc-cluster/abc-quarto-base:latest",
	"code-server": "codercom/code-server:latest",
}

const defaultImage = "ghcr.io/abc-cluster/abc-quarto-base:latest"

// JobConfig holds all parameters needed to generate a workbench Nomad job.
type JobConfig struct {
	User            string // pseudonym (e.g. lunar_hornbill) — becomes job name + volume name
	SessionID       string // WB-… ULID, stored in local.db
	Token           string // code-server password (16-char random)
	Cores           int    // CPU cores (converted to MHz for Nomad)
	MemoryMB        int
	Namespace       string // Nomad namespace, typically "abc-sessions"
	Datacenter      string // e.g. "seedling-prod"
	NodeName        string // Nomad node unique.name constraint
	NodePool        string // Nomad node pool (e.g. "platform"); defaults to "all"
	Image           string // container image; defaults to abc-quarto-base
	IDE             string // "quarto" | "code-server" (future: "positron")
	ProjectDir      string // optional; if set, code-server opens this dir
	Telemetry       bool   // whether to include the session-watcher sidecar
	IdleTimeoutSecs int

	// MinIO / S3 credentials — injected as env vars.
	// Leave all three empty to omit the env block (operator-configured cluster).
	S3Endpoint  string
	S3AccessKey string
	S3SecretKey string
}

// GenerateHCL returns a Nomad HCL service job string for a workbench session.
func GenerateHCL(c JobConfig) string {
	if c.Image == "" {
		if img, ok := ideImages[c.IDE]; ok {
			c.Image = img
		} else {
			c.Image = defaultImage
		}
	}
	if c.Namespace == "" {
		c.Namespace = "abc-sessions"
	}
	if c.Cores <= 0 {
		c.Cores = 2
	}
	if c.MemoryMB <= 0 {
		c.MemoryMB = 4096
	}
	if c.IdleTimeoutSecs <= 0 {
		c.IdleTimeoutSecs = 14400
	}
	if c.IDE == "" {
		c.IDE = "quarto"
	}
	if c.NodePool == "" {
		// "all" includes every node so the node.unique.name constraint
		// can target aither (platform pool) without a separate node_pool restriction.
		c.NodePool = "all"
	}

	cpuMHz := c.Cores * 1000

	jobID := "abc-workbench-" + c.User
	// Homedir: bind-mounted from host via docker.volumes.enabled = true.
	// Host path: /data/workbench/<user>/home  (created by abc workbench start before job submission)
	// Container path: /home/<user>
	// No Nomad host_volume registration required — eliminates per-user Nomad restarts.
	hostHomedir := "/data/workbench/" + c.User + "/home"
	homedir := "/home/" + c.User

	// s3EnvLines is injected inside the single env {} block (not a separate block).
	s3EnvLines := ""
	if c.S3Endpoint != "" && c.S3AccessKey != "" {
		s3EnvLines = fmt.Sprintf(
			"        AWS_ACCESS_KEY_ID     = %q\n"+
				"        AWS_SECRET_ACCESS_KEY = %q\n"+
				"        S3_ENDPOINT_URL       = %q\n"+
				"        MC_HOST_abc           = %q\n",
			c.S3AccessKey, c.S3SecretKey, c.S3Endpoint,
			fmt.Sprintf("https://%s:%s@%s", c.S3AccessKey, c.S3SecretKey,
				stripScheme(c.S3Endpoint)),
		)
	}

	projectEnv := ""
	if c.ProjectDir != "" {
		projectEnv = fmt.Sprintf("        PROJECT_DIR = %q\n", c.ProjectDir)
	}

	nodeConstraint := ""
	if c.NodeName != "" {
		nodeConstraint = fmt.Sprintf(`
  constraint {
    attribute = "${node.unique.name}"
    value     = %q
  }
`, c.NodeName)
	}

	return fmt.Sprintf(`# abc-workbench — generated by abc workbench start
# session_id: %s
# do not edit manually; regenerate via abc workbench start

job %q {
  namespace   = %q
  type        = "service"
  datacenters = [%q]
  node_pool   = %q
  priority    = 40
%s
  update {
    max_parallel = 1
  }

  group "workbench-session" {
    count = 1

    restart {
      attempts = 0
      mode     = "fail"
    }

    network {
      mode = "bridge"
      port "http" {
        to = 8080
      }
    }

    task "session" {
      driver       = "docker"
      kill_timeout = "120s"

      config {
        image   = %q
        ports   = ["http"]
        # Bind mount homedir via docker.volumes.enabled = true in Nomad plugin config.
        # Host path created by abc workbench start before job submission.
        # No Nomad host_volume registration required.
        volumes = [%q]
      }

      env {
        CS_PASSWORD          = %q
        PASSWORD             = %q
        CS_BIND_ADDR         = "0.0.0.0:8080"
        ABC_SESSION_ID       = %q
        ABC_USER             = %q
        ABC_IDE              = %q
        ABC_IDLE_TIMEOUT     = %q
%s%s      }

      resources {
        cpu    = %d
        memory = %d
      }

      logs {
        max_files     = 5
        max_file_size = 10
      }
    }
  }
}
`,
		c.SessionID,
		jobID, c.Namespace, c.Datacenter, c.NodePool,
		nodeConstraint,
		c.Image,
		fmt.Sprintf("%s:%s", hostHomedir, homedir),
		c.Token, c.Token,
		c.SessionID, c.User, c.IDE,
		fmt.Sprintf("%d", c.IdleTimeoutSecs),
		projectEnv,
		s3EnvLines,
		cpuMHz, c.MemoryMB,
	)
}

// stripScheme removes http:// or https:// from an endpoint URL.
func stripScheme(endpoint string) string {
	for _, pfx := range []string{"https://", "http://"} {
		if len(endpoint) > len(pfx) && endpoint[:len(pfx)] == pfx {
			return endpoint[len(pfx):]
		}
	}
	return endpoint
}
