package workbench

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"text/template"
)

// DeriveToken produces a stable 16-char hex workbench password from the user's
// MinIO secret key. Same key → same password every session. If secretKey is
// empty (e.g. operator-configured cluster), a random token should be used instead.
func DeriveToken(secretKey string) string {
	h := sha256.Sum256([]byte(secretKey))
	return fmt.Sprintf("%x", h[:8]) // 16 hex chars
}

// ideImages maps IDE name → default container image.
// quarto uses abc-quarto-base (in-house image, built separately).
// code-server uses the upstream codercom image (usable immediately for testing).
var ideImages = map[string]string{
	"quarto":      "ghcr.io/abc-cluster/abc-quarto-base:latest",
	"code-server": "codercom/code-server:latest",
}

const defaultImage = "ghcr.io/abc-cluster/abc-quarto-base:latest"

// JobConfig holds all parameters needed to generate a workbench Nomad job.
type JobConfig struct {
	User            string // pseudonym (e.g. lunar_hornbill) — becomes job name + volume name
	SessionID       string // WB-… ULID, stored in local.db
	Token           string // code-server password (16-char random)
	Cores           int    // CPU cores (converted to MHz for Nomad)
	MemoryMB        int
	Namespace       string // Nomad namespace, typically "abc-sessions"
	Datacenter      string // e.g. "seedling-prod"
	NodeName        string // Nomad node unique.name constraint
	NodePool        string // Nomad node pool (e.g. "platform"); defaults to "all"
	Image           string // container image; defaults to abc-quarto-base
	IDE             string // "quarto" | "code-server" (future: "positron")
	ProjectDir      string // optional; if set, code-server opens this dir
	Telemetry       bool   // whether to include the session-watcher sidecar
	IdleTimeoutSecs int

	// MinIO / S3 credentials — injected as env vars.
	// Leave all three empty to omit the env block (operator-configured cluster).
	S3Endpoint  string
	S3AccessKey string
	S3SecretKey string
}

// hclData is the template data struct for the Nomad HCL job.
// All fields are pre-computed from JobConfig before template execution.
type hclData struct {
	SessionID  string
	JobID      string
	Namespace  string
	Datacenter string
	NodePool   string
	NodeName   string // empty → omit constraint block
	Image      string
	// Docker bind-mount: "hostPath:containerPath"
	VolumeMount string
	// Env vars
	Token          string
	User           string
	IDE            string
	IdleTimeout    string // stringified seconds
	ProjectDir     string // empty → omit
	HasS3Creds     bool
	S3AccessKey    string
	S3SecretKey    string
	S3Endpoint     string
	MCHostABC      string // https://key:secret@endpoint (no scheme)
	// Resources
	CPUMHz   int
	MemoryMB int
}

// hclFuncs provides the quote helper (Go %q → HCL string literal).
var hclFuncs = template.FuncMap{
	"quote": func(s string) string { return fmt.Sprintf("%q", s) },
}

// workbenchHCLTmpl is the Nomad HCL template for a workbench session job.
var workbenchHCLTmpl = template.Must(
	template.New("workbench-hcl").Funcs(hclFuncs).Parse(`# abc-workbench — generated by abc workbench start
# session_id: {{.SessionID}}
# do not edit manually; regenerate via abc workbench start

job {{.JobID | quote}} {
  namespace   = {{.Namespace | quote}}
  type        = "service"
  datacenters = [{{.Datacenter | quote}}]
  node_pool   = {{.NodePool | quote}}
  priority    = 40
{{- if .NodeName}}

  constraint {
    attribute = "${node.unique.name}"
    value     = {{.NodeName | quote}}
  }
{{- end}}

  update {
    max_parallel = 1
  }

  group "workbench-session" {
    count = 1

    restart {
      attempts = 0
      mode     = "fail"
    }

    network {
      mode = "bridge"
      port "http" {
        to = 8080
      }
    }

    task "session" {
      driver       = "docker"
      kill_timeout = "120s"

      config {
        image   = {{.Image | quote}}
        ports   = ["http"]
        # Bind mount homedir via docker.volumes.enabled = true in Nomad plugin config.
        # Host path created by abc workbench start before job submission.
        # No Nomad host_volume registration required.
        volumes = [{{.VolumeMount | quote}}]
      }

      env {
        CS_PASSWORD      = {{.Token | quote}}
        PASSWORD         = {{.Token | quote}}
        CS_BIND_ADDR     = "0.0.0.0:8080"
        ABC_SESSION_ID   = {{.SessionID | quote}}
        ABC_USER         = {{.User | quote}}
        ABC_IDE          = {{.IDE | quote}}
        ABC_IDLE_TIMEOUT = {{.IdleTimeout | quote}}
{{- if .ProjectDir}}
        PROJECT_DIR = {{.ProjectDir | quote}}
{{- end}}
{{- if .HasS3Creds}}
        AWS_ACCESS_KEY_ID     = {{.S3AccessKey | quote}}
        AWS_SECRET_ACCESS_KEY = {{.S3SecretKey | quote}}
        S3_ENDPOINT_URL       = {{.S3Endpoint | quote}}
        MC_HOST_abc           = {{.MCHostABC | quote}}
{{- end}}
      }

      resources {
        cpu    = {{.CPUMHz}}
        memory = {{.MemoryMB}}
      }

      logs {
        max_files     = 5
        max_file_size = 10
      }
    }
  }
}
`))

// GenerateHCL returns a Nomad HCL service job string for a workbench session.
func GenerateHCL(c JobConfig) string {
	// Apply defaults.
	if c.Image == "" {
		if img, ok := ideImages[c.IDE]; ok {
			c.Image = img
		} else {
			c.Image = defaultImage
		}
	}
	if c.Namespace == "" {
		c.Namespace = "abc-sessions"
	}
	if c.Cores <= 0 {
		c.Cores = 2
	}
	if c.MemoryMB <= 0 {
		c.MemoryMB = 4096
	}
	if c.IdleTimeoutSecs <= 0 {
		c.IdleTimeoutSecs = 14400
	}
	if c.IDE == "" {
		c.IDE = "quarto"
	}
	if c.NodePool == "" {
		// "all" includes every node so the node.unique.name constraint
		// can target aither (platform pool) without a separate node_pool restriction.
		c.NodePool = "all"
	}

	hostHomedir := "/data/workbench/" + c.User + "/home"
	homedir := "/home/" + c.User

	data := hclData{
		SessionID:   c.SessionID,
		JobID:       "abc-workbench-" + c.User,
		Namespace:   c.Namespace,
		Datacenter:  c.Datacenter,
		NodePool:    c.NodePool,
		NodeName:    c.NodeName,
		Image:       c.Image,
		VolumeMount: hostHomedir + ":" + homedir,
		Token:       c.Token,
		User:        c.User,
		IDE:         c.IDE,
		IdleTimeout: fmt.Sprintf("%d", c.IdleTimeoutSecs),
		ProjectDir:  c.ProjectDir,
		CPUMHz:      c.Cores * 1000,
		MemoryMB:    c.MemoryMB,
	}

	if c.S3Endpoint != "" && c.S3AccessKey != "" {
		data.HasS3Creds = true
		data.S3AccessKey = c.S3AccessKey
		data.S3SecretKey = c.S3SecretKey
		data.S3Endpoint = c.S3Endpoint
		data.MCHostABC = fmt.Sprintf("https://%s:%s@%s",
			c.S3AccessKey, c.S3SecretKey, stripScheme(c.S3Endpoint))
	}

	var buf bytes.Buffer
	if err := workbenchHCLTmpl.Execute(&buf, data); err != nil {
		// Template errors are programming errors — panic so they surface in tests.
		panic(fmt.Sprintf("workbench HCL template: %v", err))
	}
	return buf.String()
}

// stripScheme removes http:// or https:// from an endpoint URL.
func stripScheme(endpoint string) string {
	for _, pfx := range []string{"https://", "http://"} {
		if len(endpoint) > len(pfx) && endpoint[:len(pfx)] == pfx {
			return endpoint[len(pfx):]
		}
	}
	return endpoint
}
