#!/usr/bin/env bash
# bootstrap-secrets.sh
#
# Generate and persist secrets required by the systemd-managed HashiCorp stack
# BEFORE deploying those services.
#
# Run this script ONCE after Vault has been initialized (vault-keys.env exists).
# Safe to re-run: skips key generation if acl/boundary-controller.env exists.
#
# Architecture
# ────────────
#  Vault unseal keys   → already in acl/vault-keys.env (from init-vault.sh)
#                        deploy-vault.sh reads that file and writes /etc/vault.d/vault.env
#
#  Boundary KMS keys   → written to acl/boundary-controller.env (by this script)
#                        deploy-boundary-controller.sh reads it and embeds keys in controller.hcl
#
#  Worker auth key     → also written to Nomad variable "nomad/jobs/abc-nodes-boundary-worker"
#                        so the boundary-worker system job can read it via nomadVar
#
# Usage
# ─────
#   cd <repo-root>
#   bash deployments/abc-nodes/vault/bootstrap-secrets.sh
#
# Prerequisites
# ─────────────
#   openssl — for key generation
#   nomad   — CLI in PATH with NOMAD_ADDR + NOMAD_TOKEN (for the worker var only)
#   acl/vault-keys.env must exist (generated by experimental/scripts/init-vault.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

KEYS_FILE="${KEYS_FILE:-${DEPLOY_ROOT}/acl/vault-keys.env}"
BOUNDARY_ENV_FILE="${BOUNDARY_ENV_FILE:-${DEPLOY_ROOT}/acl/boundary-controller.env}"
NOMAD_NAMESPACE="${NOMAD_NAMESPACE:-abc-services}"

echo "==> bootstrap-secrets"
echo "    Vault keys:      ${KEYS_FILE}"
echo "    Boundary env:    ${BOUNDARY_ENV_FILE}"
echo "    Nomad namespace: ${NOMAD_NAMESPACE}"
echo ""

# ── Check prerequisites ───────────────────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl not in PATH" >&2; exit 1; }

if [[ ! -f "${KEYS_FILE}" ]]; then
  echo "ERROR: Vault keys file not found: ${KEYS_FILE}" >&2
  echo "  Run deployments/abc-nodes/experimental/scripts/init-vault.sh first." >&2
  exit 1
fi

# Verify vault keys are present
# shellcheck source=/dev/null
source "${KEYS_FILE}"
for v in VAULT_UNSEAL_KEY_1 VAULT_UNSEAL_KEY_2 VAULT_UNSEAL_KEY_3; do
  [[ -n "${!v:-}" ]] || { echo "ERROR: ${v} not set in ${KEYS_FILE}" >&2; exit 1; }
done
echo "==> Vault unseal keys verified in ${KEYS_FILE}"
echo "    (deploy-vault.sh will upload them to /etc/vault.d/vault.env on aither)"
echo ""

# ── Generate Boundary KMS keys → acl/boundary-controller.env ─────────────────
#
# These keys must NOT change after Boundary is initialized.
# Regenerating them requires wiping the Boundary database (destructive).
# The env file is chmod 600 and .gitignored.

if [[ -f "${BOUNDARY_ENV_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${BOUNDARY_ENV_FILE}"
  if [[ -n "${BOUNDARY_ROOT_KEY:-}" && -n "${BOUNDARY_WORKER_AUTH_KEY:-}" && -n "${BOUNDARY_RECOVERY_KEY:-}" ]]; then
    echo "==> ${BOUNDARY_ENV_FILE} already exists with all three KMS keys — skipping generation."
    echo "    (Delete it to regenerate: rm ${BOUNDARY_ENV_FILE})"
    echo "    WARNING: regenerating keys requires wiping the Boundary database."
    echo ""
  else
    echo "ERROR: ${BOUNDARY_ENV_FILE} exists but is missing keys. Check the file." >&2
    exit 1
  fi
else
  echo "==> Generating Boundary AEAD KMS keys..."

  ROOT_KEY=$(openssl rand -base64 32)
  WORKER_AUTH_KEY=$(openssl rand -base64 32)
  RECOVERY_KEY=$(openssl rand -base64 32)

  cat > "${BOUNDARY_ENV_FILE}" <<EOF
# Boundary controller secrets — generated by bootstrap-secrets.sh
# chmod 600, never commit to git.
# CRITICAL: do not regenerate after Boundary is initialized — keys are
# baked into the encrypted database and cannot be changed without a wipe.
BOUNDARY_ROOT_KEY=${ROOT_KEY}
BOUNDARY_WORKER_AUTH_KEY=${WORKER_AUTH_KEY}
BOUNDARY_RECOVERY_KEY=${RECOVERY_KEY}
EOF
  chmod 600 "${BOUNDARY_ENV_FILE}"
  echo "    Written to: ${BOUNDARY_ENV_FILE}"
  echo ""
fi

# Re-load so the worker var step can read them even when they already existed
# shellcheck source=/dev/null
source "${BOUNDARY_ENV_FILE}"

# ── Write worker-auth key to Nomad variable ───────────────────────────────────
#
# The boundary-worker system job (boundary-worker.nomad.hcl) uses KMS auth and
# reads the worker-auth key from Nomad variable "nomad/jobs/abc-nodes-boundary-worker".
# The controller reads the same key from the generated controller.hcl.

if command -v nomad >/dev/null 2>&1; then
  echo "==> Writing worker-auth key to Nomad variable (for boundary-worker job)..."

  # Token resolution order:
  #   1. NOMAD_TOKEN env var (explicitly set by caller)
  #   2. abc CLI config (~/.abc/config.yaml) — has variable write access
  #   3. Fail with instructions
  if [[ -z "${NOMAD_TOKEN:-}" ]]; then
    ABC_NOMAD_TOKEN=$(python3 -c "
import yaml, sys
try:
    cfg = yaml.safe_load(open('${HOME}/.abc/config.yaml'))
    # Walk nested structure looking for nomad_token
    def find(d):
        if isinstance(d, dict):
            if 'nomad_token' in d and d['nomad_token']: return d['nomad_token']
            for v in d.values():
                r = find(v)
                if r: return r
        elif isinstance(d, list):
            for v in d:
                r = find(v)
                if r: return r
    print(find(cfg) or '')
except: print('')
" 2>/dev/null || echo "")
    if [[ -n "${ABC_NOMAD_TOKEN}" ]]; then
      export NOMAD_TOKEN="${ABC_NOMAD_TOKEN}"
      echo "    Using token from ~/.abc/config.yaml"
    fi
  fi

  if [[ -z "${NOMAD_TOKEN:-}" ]]; then
    echo "    WARNING: NOMAD_TOKEN not set and ~/.abc/config.yaml token not found."
    echo "    Set NOMAD_TOKEN and re-run, or write the var manually:"
    echo "      nomad var put -namespace=${NOMAD_NAMESPACE} -force \\"
    echo "        nomad/jobs/abc-nodes-boundary-worker \\"
    echo "        worker_auth_key=\"\${BOUNDARY_WORKER_AUTH_KEY}\""
  else
    nomad var put \
      -namespace="${NOMAD_NAMESPACE}" \
      -force \
      "nomad/jobs/abc-nodes-boundary-worker" \
      worker_auth_key="${BOUNDARY_WORKER_AUTH_KEY}"
    echo "    ✓ nomad/jobs/abc-nodes-boundary-worker updated"
  fi
else
  echo "    (nomad not in PATH — skipping Nomad variable write)"
  echo "    Run manually after nomad CLI is available:"
  echo "      nomad var put -namespace=${NOMAD_NAMESPACE} -force \\"
  echo "        nomad/jobs/abc-nodes-boundary-worker \\"
  echo "        worker_auth_key=\"\${BOUNDARY_WORKER_AUTH_KEY}\""
fi

echo ""

# ── Summary ───────────────────────────────────────────────────────────────────
cat <<SUMMARY
══════════════════════════════════════════════════════
  Bootstrap complete.

  Secrets on disk:
    acl/vault-keys.env            — Vault unseal keys (existing)
    acl/boundary-controller.env   — Boundary KMS keys (generated/verified)

  Deploy order:
    1.  bash deployments/abc-nodes/vault/deploy-vault.sh
             → installs vault.service, uploads vault-keys.env as /etc/vault.d/vault.env

    2.  bash deployments/abc-nodes/boundary/deploy-boundary-controller.sh
             → installs boundary-controller.service, embeds KMS keys in controller.hcl

    3.  abc admin services nomad cli -- job run \\
          deployments/abc-nodes/nomad/boundary-worker.nomad.hcl
             → system job, reads worker_auth_key from nomad var

    4.  Configure Vault SSH CA (once vault is running):
          export VAULT_ADDR=http://vault.aither
          export VAULT_TOKEN=\$VAULT_ROOT_TOKEN   # from acl/vault-keys.env
          bash deployments/abc-nodes/vault/setup-ssh-ca.sh

    5.  Register SSH targets in Boundary:
          bash deployments/abc-nodes/boundary/setup-boundary.sh
══════════════════════════════════════════════════════
SUMMARY
