#!/usr/bin/env bash
# configure-node.sh
#
# Trust the Vault SSH CA on a target SSH host.
#
# After running this script on a host, any SSH certificate signed by the
# Vault SSH CA will be accepted for login — no need to pre-install user
# public keys. Users sign their key with Vault and SSH directly in.
#
# What it does
# ────────────
#  1. Copies the Vault CA public key to the target node
#  2. Configures sshd to trust it via TrustedUserCAKeys
#  3. Reloads sshd
#
# Usage
# ─────
#   bash deployments/abc-nodes/vault/configure-node.sh --node sun-aither
#   bash deployments/abc-nodes/vault/configure-node.sh --node sun-node2
#
#   Override CA key file:
#   CA_KEY_FILE=/path/to/vault_ssh_ca.pub ./configure-node.sh --node sun-aither
#
# Prerequisites
# ─────────────
#  • SSH access to the target node (via ssh config or sshpass)
#  • sudo rights on the target node
#  • vault/vault_ssh_ca.pub (generated by setup-ssh-ca.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CA_KEY_FILE="${CA_KEY_FILE:-${SCRIPT_DIR}/vault_ssh_ca.pub}"
REMOTE_CA_KEY="/etc/ssh/vault_ssh_ca.pub"
SSHD_CONFIG="/etc/ssh/sshd_config"
REMOTE_HOST=""
PASS_FILE="${PASS_FILE:-$HOME/.ssh/pass.sun-aither}"

# ── Parse arguments ───────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --node|-n) REMOTE_HOST="$2"; shift 2 ;;
    --ca-key)  CA_KEY_FILE="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -n "${REMOTE_HOST}" ]] || { echo "ERROR: --node <hostname> required" >&2; exit 1; }
[[ -f "${CA_KEY_FILE}" ]] || { echo "ERROR: CA key file not found: ${CA_KEY_FILE}" >&2
  echo "  Run vault/setup-ssh-ca.sh first." >&2; exit 1; }

# ── SSH helpers ───────────────────────────────────────────────────────────────
if [[ -f "${PASS_FILE}" ]]; then
  SSH="sshpass -f ${PASS_FILE} ssh -o StrictHostKeyChecking=no ${REMOTE_HOST}"
  SCP="sshpass -f ${PASS_FILE} scp -o StrictHostKeyChecking=no"
  PASS="$(cat "${PASS_FILE}")"
else
  SSH="ssh -o StrictHostKeyChecking=no ${REMOTE_HOST}"
  SCP="scp -o StrictHostKeyChecking=no"
  PASS=""
fi

echo "==> Configure node: ${REMOTE_HOST}"
echo "    CA key: ${CA_KEY_FILE}"
echo ""

# ── 1. Copy CA public key to target ─────────────────────────────────────────
echo "==> Copying CA public key to ${REMOTE_HOST}:${REMOTE_CA_KEY}"
${SCP} "${CA_KEY_FILE}" "${REMOTE_HOST}:/tmp/vault_ssh_ca.pub"

# ── 2. Install CA key and update sshd_config ─────────────────────────────────
echo "==> Installing CA key and updating sshd_config"
if [[ -n "${PASS}" ]]; then
  echo "${PASS}" | ${SSH} "sudo -S bash -s" <<'REMOTE'
set -e
cp /tmp/vault_ssh_ca.pub /etc/ssh/vault_ssh_ca.pub
chmod 644 /etc/ssh/vault_ssh_ca.pub

# Add TrustedUserCAKeys if not already present
if ! grep -q "TrustedUserCAKeys" /etc/ssh/sshd_config; then
  echo "TrustedUserCAKeys /etc/ssh/vault_ssh_ca.pub" >> /etc/ssh/sshd_config
  echo "  Added TrustedUserCAKeys to sshd_config"
else
  # Update the existing TrustedUserCAKeys line
  sed -i "s|^#*\s*TrustedUserCAKeys.*|TrustedUserCAKeys /etc/ssh/vault_ssh_ca.pub|" /etc/ssh/sshd_config
  echo "  Updated TrustedUserCAKeys in sshd_config"
fi

echo "  Reloading sshd..."
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || service ssh reload
echo "  sshd reloaded"
REMOTE
else
  ${SSH} "sudo bash -s" <<'REMOTE'
set -e
cp /tmp/vault_ssh_ca.pub /etc/ssh/vault_ssh_ca.pub
chmod 644 /etc/ssh/vault_ssh_ca.pub

if ! grep -q "TrustedUserCAKeys" /etc/ssh/sshd_config; then
  echo "TrustedUserCAKeys /etc/ssh/vault_ssh_ca.pub" >> /etc/ssh/sshd_config
  echo "  Added TrustedUserCAKeys to sshd_config"
else
  sed -i "s|^#*\s*TrustedUserCAKeys.*|TrustedUserCAKeys /etc/ssh/vault_ssh_ca.pub|" /etc/ssh/sshd_config
  echo "  Updated TrustedUserCAKeys in sshd_config"
fi

echo "  Reloading sshd..."
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || service ssh reload
echo "  sshd reloaded"
REMOTE
fi

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Node ${REMOTE_HOST} is now configured to trust the Vault SSH CA."
echo ""
echo "  Test: sign a key and SSH in:"
echo "    export VAULT_ADDR=http://vault.aither"
echo "    export VAULT_TOKEN=<user-token>"
echo "    vault write -field=signed_key \\"
echo "      ssh-client-signer/sign/ssh-role \\"
echo "      public_key=@~/.ssh/id_rsa.pub \\"
echo "      valid_principals=ubuntu \\"
echo "    > ~/.ssh/signed-cert.pub"
echo "    ssh -i ~/.ssh/id_rsa -i ~/.ssh/signed-cert.pub ubuntu@${REMOTE_HOST}"
echo "══════════════════════════════════════════════════════"
