package slug

// Adjectives is a curated list of ~150 inoffensive adjectives suitable for
// human-friendly slugs. ASCII-only.
var Adjectives = []string{
	"agile", "amber", "ancient", "azure", "balmy", "blazing", "bold", "brave",
	"breezy", "bright", "brisk", "bronze", "calm", "candid", "carefree",
	"caring", "cheerful", "clever", "cosmic", "courageous", "creative",
	"crimson", "crisp", "curious", "daring", "dawn", "dazzling", "deep",
	"determined", "diligent", "dreamy", "dusky", "earnest", "eager", "easy",
	"electric", "elegant", "emerald", "epic", "ethereal", "exotic", "fair",
	"fancy", "faithful", "fiery", "flawless", "fluffy", "fond", "fragrant",
	"frosty", "gallant", "gentle", "giddy", "gilded", "glassy", "gleaming",
	"glowing", "golden", "graceful", "grand", "grassy", "happy", "hardy",
	"harmonic", "hazy", "hearty", "heavenly", "hidden", "honest", "hopeful",
	"humble", "icy", "idyllic", "indigo", "ivory", "jade", "jolly", "joyful",
	"jovial", "kind", "lavender", "lively", "logical", "loyal", "lucid",
	"lucky", "lunar", "luminous", "magnetic", "majestic", "mellow", "merry",
	"misty", "modest", "mossy", "noble", "nostalgic", "obsidian", "ocean",
	"orchid", "patient", "peaceful", "peachy", "pearly", "peppy", "placid",
	"plucky", "poised", "polished", "polar", "proud", "pumice", "purple",
	"quaint", "quiet", "quick", "radiant", "regal", "resolute", "ripe",
	"rosy", "rustic", "saffron", "sapphire", "scarlet", "serene", "shiny",
	"silken", "silver", "smooth", "snowy", "solar", "sonic", "spirited",
	"splendid", "starry", "steady", "still", "stoic", "stormy", "sturdy",
	"sublime", "summery", "sunny", "swift", "tame", "tender", "thoughtful",
	"thriving", "tidy", "topaz", "tranquil", "turquoise", "twilit", "vermilion",
	"vibrant", "violet", "vivid", "warm", "watery", "wavy", "wholesome",
	"witty", "woolly", "young", "zealous", "zesty",
}

// Nouns is a curated list of ~150 inoffensive nouns. Animals, objects,
// natural phenomena. ASCII-only.
var Nouns = []string{
	"acorn", "albatross", "alder", "almond", "anchor", "antelope", "apple",
	"aspen", "badger", "bamboo", "banyan", "basil", "bay", "beacon", "beaver",
	"beech", "beetle", "bison", "blossom", "bramble", "branch", "brook",
	"buffalo", "butterfly", "cactus", "camel", "canyon", "cardinal", "cedar",
	"cheetah", "cherry", "chestnut", "clover", "coast", "cobalt", "comet",
	"compass", "coral", "cottage", "cougar", "coyote", "crane", "crayon",
	"creek", "crocus", "crow", "cypress", "daffodil", "dahlia", "dandelion",
	"dawn", "daybreak", "delta", "dewdrop", "dolphin", "dragonfly", "drift",
	"eagle", "echo", "elder", "elm", "ember", "estuary", "falcon", "fawn",
	"fern", "ferret", "field", "finch", "fjord", "flame", "fleece", "flora",
	"forest", "fox", "frost", "fuchsia", "gazelle", "geode", "glacier",
	"glade", "glow", "goldfinch", "grove", "harbor", "hare", "harvest",
	"hawk", "hazel", "heath", "heron", "highland", "hill", "horizon", "ibis",
	"iris", "ivy", "jackal", "jasmine", "jay", "juniper", "kestrel", "lagoon",
	"lantern", "larch", "lark", "lavender", "leopard", "lichen", "lily",
	"linnet", "lotus", "lynx", "magnolia", "mallow", "maple", "marigold",
	"meadow", "mistral", "moose", "mountain", "moth", "mulberry", "nebula",
	"nightingale", "oak", "ocean", "olive", "orchid", "osprey", "otter",
	"owl", "panda", "pansy", "paper", "pebble", "pelican", "petrel", "pine",
	"plover", "poplar", "prairie", "puffin", "quail", "quartz", "quokka",
	"rabbit", "rainfall", "raven", "reef", "rhododendron", "ridge", "river",
	"robin", "rose", "saffron", "salmon", "sandpiper", "savanna", "sequoia",
	"shore", "skylark", "snowdrop", "sparrow", "spruce", "starling", "stoat",
	"stream", "sunflower", "swallow", "swan", "swallowtail", "sycamore",
	"thistle", "thrush", "tulip", "turtle", "valley", "violet", "warbler",
	"willow", "winter", "wisteria", "wolf", "woodland", "yarrow", "zebra",
}
