package data

import (
	"fmt"
	"os"
	"path/filepath"

	"filippo.io/age/plugin"
	"github.com/spf13/cobra"

	abccfg "github.com/abc-cluster/abc-cluster-cli/internal/config"
	"github.com/abc-cluster/abc-cluster-cli/internal/keysource"
)

// newKEKProvider builds a managed-KEK provider (abccrypt.KEKProvider) for the
// active context, backed by the broker's POST /keys/get. It performs NO network
// call by itself — the provider fetches (and caches) the group KEK lazily on the
// first Wrap/Unwrap, so adding it as a decrypt identity is free unless the file
// actually carries an abc stanza.
//
// Used by the managed-encryption default: encrypt names the abc recipient with
// the caller's own kek_id (via prov.OwnKekID); decrypt offers the abc identity
// so managed files open with no passphrase.
func newKEKProvider(cmd *cobra.Command, cfg *abccfg.Config) (*keysource.Provider, error) {
	ctx, ok := cfg.ContextNamed(cfg.ResolveContextName(cfg.ActiveContext))
	if !ok {
		return nil, fmt.Errorf("no active context — run 'abc auth login' or claim a slot first")
	}
	cl, err := keysource.NewClient(ctx)
	if err != nil {
		return nil, err
	}
	return keysource.NewProvider(cmd.Context(), cl), nil
}

// materializeAgeRecipient writes the active group's age recipient (age1abc1…) to
// ~/.abc/age/recipients.txt so stock age can encrypt managed files with
// `age -e -R ~/.abc/age/recipients.txt <file>` — no new `abc keys` command, no
// copy-pasted key string. The recipient is non-secret (it only names the group
// KEK, which the broker still membership-gates at /keys/get). Best-effort: a
// write failure is a note, not a fatal — managed encryption via `abc` is unaffected.
func materializeAgeRecipient(cmd *cobra.Command, kekID string) {
	rcpt := plugin.EncodeRecipient("abc", []byte(kekID))
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	dir := filepath.Join(home, ".abc", "age")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not create %s: %v)\n", dir, err)
		return
	}
	path := filepath.Join(dir, "recipients.txt")
	content := "# abc managed age recipient for " + kekID + " (regenerated by `abc data encrypt`).\n" +
		"# Stock age:  age -e -R " + path + " <file>   |   age -d -j abc <file>.age\n" +
		rcpt + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not write %s: %v)\n", path, err)
	}
}
