package data

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	abccfg "github.com/abc-cluster/abc-cluster-cli/internal/config"
	"github.com/abc-cluster/abc-cluster-cli/internal/keysource"
)

// groupOfContext derives the group name a context belongs to, from its namespace
// (su-<group>) — the field that "mentions" the group in ~/.abc/config.yaml.
func groupOfContext(c abccfg.Context) string {
	return strings.TrimPrefix(strings.TrimSpace(c.Namespace), "su-")
}

// resolveManagedContext picks the context to use for a managed crypt op.
//
//   - group == ""  → the active context; kek_id "" lets the broker derive the group.
//   - group != ""  → the context whose group (name or namespace su-<g>) matches, so a
//     user who is a member of several groups (one context per group, ADR-0057) can
//     target one per command without `abc context use`. kek_id "group:<g>" is sent as
//     a cross-check (the broker 403s if that context's slot is a different group).
func resolveManagedContext(cfg *abccfg.Config, group string) (name string, ctx abccfg.Context, kekID string, err error) {
	group = strings.TrimSpace(group)
	if group == "" {
		n := cfg.ResolveContextName(cfg.ActiveContext)
		c, ok := cfg.ContextNamed(n)
		if !ok {
			return "", abccfg.Context{}, "", fmt.Errorf("no active context — run 'abc auth login' or claim a slot first")
		}
		return n, c, "", nil
	}
	var matches []string
	for n, c := range cfg.Contexts {
		if n == group || groupOfContext(c) == group {
			matches = append(matches, n)
		}
	}
	sort.Strings(matches)
	switch len(matches) {
	case 1:
		c, _ := cfg.ContextNamed(matches[0])
		return matches[0], c, "group:" + group, nil
	case 0:
		return "", abccfg.Context{}, "", fmt.Errorf(
			"no context found for group %q — each group is its own context (ADR-0057).\n"+
				"  Available: %s\n  Claim a slot in %q, or pick one with: abc context use <name>",
			group, contextGroupSummary(cfg), group)
	default:
		return "", abccfg.Context{}, "", fmt.Errorf(
			"%d contexts match group %q (%s) — disambiguate with: abc context use <name>",
			len(matches), group, strings.Join(matches, ", "))
	}
}

// contextGroupSummary lists "ctx (group)" for error messages.
func contextGroupSummary(cfg *abccfg.Config) string {
	var out []string
	for n, c := range cfg.Contexts {
		if g := groupOfContext(c); g != "" {
			out = append(out, fmt.Sprintf("%s (%s)", n, g))
		} else {
			out = append(out, n)
		}
	}
	sort.Strings(out)
	if len(out) == 0 {
		return "(no contexts)"
	}
	return strings.Join(out, ", ")
}

// newGroupKeyProvider builds a managed-key provider for the context selected by
// group ("" = active), backed by the broker's POST /keys/get. It performs NO
// network call by itself — the provider releases (and caches) the key lazily.
func newGroupKeyProvider(cmd *cobra.Command, cfg *abccfg.Config, group string) (*keysource.Provider, error) {
	_, ctx, kekID, err := resolveManagedContext(cfg, group)
	if err != nil {
		return nil, err
	}
	cl, err := keysource.NewClient(ctx)
	if err != nil {
		return nil, err
	}
	return keysource.NewProvider(cmd.Context(), cl, kekID), nil
}

// materializeAgeKeyFiles writes the group's native age artifacts under ~/.abc/age
// so the user can use STOCK age with no plugin:
//
//	recipients.txt  — the group's age1… recipient (non-secret)  → age -e -R …
//	identity.txt    — the group's AGE-SECRET-KEY-1… (0600)       → age -d -i …
//
// No `abc keys` command: these appear as a side effect of `abc data encrypt`.
// Best-effort — a write failure is a note, not fatal (abc's own crypt is unaffected).
func materializeAgeKeyFiles(cmd *cobra.Command, gk *keysource.GroupKey) {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	dir := filepath.Join(home, ".abc", "age")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not create %s: %v)\n", dir, err)
		return
	}
	rPath := filepath.Join(dir, "recipients.txt")
	rBody := "# abc managed age recipient for " + gk.KekID + " (regenerated by `abc data encrypt`).\n" +
		"# Stock age:  age -e -R " + rPath + " <file>\n" + gk.Recipient + "\n"
	if err := os.WriteFile(rPath, []byte(rBody), 0o644); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not write %s: %v)\n", rPath, err)
	}
	iPath := filepath.Join(dir, "identity.txt")
	iBody := "# abc managed age identity (group private key) for " + gk.KekID + " — keep private.\n" +
		"# Stock age:  age -d -i " + iPath + " <file>.age\n" + gk.Identity + "\n"
	if err := os.WriteFile(iPath, []byte(iBody), 0o600); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not write %s: %v)\n", iPath, err)
	}
}
