package data

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	abccfg "github.com/abc-cluster/abc-cluster-cli/internal/config"
	"github.com/abc-cluster/abc-cluster-cli/internal/keysource"
)

// newGroupKeyProvider builds a managed-key provider for the active context,
// backed by the broker's POST /keys/get. It performs NO network call by itself —
// the provider releases (and caches) the group key lazily on first use.
func newGroupKeyProvider(cmd *cobra.Command, cfg *abccfg.Config) (*keysource.Provider, error) {
	ctx, ok := cfg.ContextNamed(cfg.ResolveContextName(cfg.ActiveContext))
	if !ok {
		return nil, fmt.Errorf("no active context — run 'abc auth login' or claim a slot first")
	}
	cl, err := keysource.NewClient(ctx)
	if err != nil {
		return nil, err
	}
	return keysource.NewProvider(cmd.Context(), cl), nil
}

// materializeAgeKeyFiles writes the group's native age artifacts under ~/.abc/age
// so the user can use STOCK age with no plugin:
//
//	recipients.txt  — the group's age1… recipient (non-secret)  → age -e -R …
//	identity.txt    — the group's AGE-SECRET-KEY-1… (0600)       → age -d -i …
//
// No `abc keys` command: these appear as a side effect of `abc data encrypt`.
// Best-effort — a write failure is a note, not fatal (abc's own crypt is unaffected).
func materializeAgeKeyFiles(cmd *cobra.Command, gk *keysource.GroupKey) {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	dir := filepath.Join(home, ".abc", "age")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not create %s: %v)\n", dir, err)
		return
	}
	rPath := filepath.Join(dir, "recipients.txt")
	rBody := "# abc managed age recipient for " + gk.KekID + " (regenerated by `abc data encrypt`).\n" +
		"# Stock age:  age -e -R " + rPath + " <file>\n" + gk.Recipient + "\n"
	if err := os.WriteFile(rPath, []byte(rBody), 0o644); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not write %s: %v)\n", rPath, err)
	}
	iPath := filepath.Join(dir, "identity.txt")
	iBody := "# abc managed age identity (group private key) for " + gk.KekID + " — keep private.\n" +
		"# Stock age:  age -d -i " + iPath + " <file>.age\n" + gk.Identity + "\n"
	if err := os.WriteFile(iPath, []byte(iBody), 0o600); err != nil {
		fmt.Fprintf(cmd.ErrOrStderr(), "  (note: could not write %s: %v)\n", iPath, err)
	}
}
