package compute

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/abc-cluster/abc-cluster-cli/cmd/utils"
	"github.com/spf13/cobra"
)

// Phase 1 of abc-node-probe-improvements (2026-05-08): nightly periodic
// re-probe of every cluster node. Generates and registers (or prints) a
// Nomad sysbatch + periodic job. The job is intentionally generated by
// the CLI rather than checked in as a static .nomad.hcl so that
// per-cluster overrides (cron, namespace, datacenter, pushgateway,
// jurisdiction, history-file path) flow through uniformly via flags or
// config, and so the schedule can be re-installed (replaced) idempotently
// from any operator workstation.

const (
	// ProbeScheduleJobID is the Nomad job ID for the periodic probe.
	ProbeScheduleJobID = "abc-node-probe-periodic"
	// ProbeScheduleDefaultNamespace is the default Nomad namespace.
	ProbeScheduleDefaultNamespace = "abc-automations"
	// ProbeScheduleDefaultCron runs nightly at 03:00 UTC.
	ProbeScheduleDefaultCron = "0 3 * * *"
	// ProbeScheduleDefaultHistoryFile is the host-local JSON-lines path.
	ProbeScheduleDefaultHistoryFile = "/var/lib/abc/probe-history.jsonl"
)

// probeScheduleTemplate renders the periodic sysbatch HCL. Mirrors the
// shape of NodeProbeJobTemplate (one-shot probe) but adds the periodic
// stanza and writes to the history-file + pushgateway sinks.
var probeScheduleTemplate = template.Must(template.New("probe_schedule").Parse(`job {{printf "%q" .JobID}} {
  type        = "sysbatch"
  datacenters = [{{printf "%q" .Datacenter}}]
  namespace   = {{printf "%q" .Namespace}}

  periodic {
    crons             = [{{printf "%q" .Cron}}]
    prohibit_overlap  = {{.ProhibitOverlap}}
    time_zone         = {{printf "%q" .TimeZone}}
  }

  meta {
    binary_path  = {{printf "%q" .BinaryPath}}
    history_file = {{printf "%q" .HistoryFile}}
    pushgateway  = {{printf "%q" .Pushgateway}}
    jurisdiction = {{printf "%q" .Jurisdiction}}
  }

  group "probe" {
    restart {
      attempts = 1
      interval = "10m"
      delay    = "30s"
      mode     = "fail"
    }

    task "run" {
      driver = "raw_exec"

      config {
        command = "${NOMAD_META_binary_path}"
        args    = {{.ArgsHCL}}
      }

      resources {
        cpu    = {{.CPU}}
        memory = {{.Memory}}
      }
    }
  }
}
`))

type probeScheduleParams struct {
	JobID           string
	Datacenter      string
	Namespace       string
	Cron            string
	TimeZone        string
	ProhibitOverlap bool
	BinaryPath      string
	HistoryFile     string
	Pushgateway     string
	Jurisdiction    string
	ArgsHCL         string
	CPU             int
	Memory          int
}

func newProbeScheduleCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "probe-schedule",
		Short: "Install or update the nightly per-node abc-node-probe periodic job",
		Long: `Generate and register a Nomad sysbatch + periodic job that runs
abc-node-probe on every cluster node on a cron schedule. Each invocation
writes a JSON-line to a host-local history file and pushes Prometheus
metrics to the configured pushgateway.

Re-running this command replaces the existing schedule with the new
parameters (Nomad's RegisterJob is upsert-style on the same job ID).

  abc infra compute probe-schedule --sudo
  abc infra compute probe-schedule --sudo --cron="0 */6 * * *" --jurisdiction=ZA
  abc infra compute probe-schedule --sudo --push-prometheus=http://pushgateway.service.consul:9091
  abc infra compute probe-schedule --dry-run

To stop the schedule, use the underlying Nomad CLI:
  abc admin services nomad cli -- job stop -purge ` + ProbeScheduleJobID + `
`,
		RunE: runProbeSchedule,
	}
	cmd.Flags().String("cron", ProbeScheduleDefaultCron,
		"Cron expression for the periodic schedule (default: nightly at 03:00)")
	cmd.Flags().String("time-zone", "UTC",
		"Time zone for the cron expression")
	cmd.Flags().String("namespace", ProbeScheduleDefaultNamespace,
		"Nomad namespace to register the periodic job into")
	cmd.Flags().String("datacenter", "",
		"Nomad datacenter (defaults to dc1 if not set)")
	cmd.Flags().String("jurisdiction", utils.EnvOrDefault("ABC_PROBE_JURISDICTION"),
		"Probe --jurisdiction value (ISO-3166 alpha-2)")
	cmd.Flags().String("binary-path", NodeProbeInstalledPath,
		"Path to the abc-node-probe binary on each cluster node")
	cmd.Flags().String("history-file", ProbeScheduleDefaultHistoryFile,
		"Host-local JSON-lines path the probe appends to on each run")
	cmd.Flags().String("push-prometheus", "",
		"Pushgateway endpoint URL (empty = pushgateway sink disabled)")
	cmd.Flags().String("skip-categories", "",
		"Probe --skip-categories value")
	cmd.Flags().Bool("prohibit-overlap", true,
		"Refuse to start a new probe alloc on a node where the previous one is still running")
	cmd.Flags().Int("cpu", 200, "Per-task CPU resource (MHz)")
	cmd.Flags().Int("memory", 256, "Per-task memory resource (MB)")
	cmd.Flags().Bool("dry-run", false,
		"Print the rendered HCL to stdout and exit without registering")
	return cmd
}

func runProbeSchedule(cmd *cobra.Command, _ []string) error {
	dryRun, _ := cmd.Flags().GetBool("dry-run")
	if !dryRun {
		if err := requireSudo(cmd); err != nil {
			return err
		}
	}

	dc, _ := cmd.Flags().GetString("datacenter")
	if dc == "" {
		dc = "dc1"
	}

	params := probeScheduleParams{
		JobID:           ProbeScheduleJobID,
		Datacenter:      dc,
		Namespace:       getStringFlag(cmd, "namespace", ProbeScheduleDefaultNamespace),
		Cron:            getStringFlag(cmd, "cron", ProbeScheduleDefaultCron),
		TimeZone:        getStringFlag(cmd, "time-zone", "UTC"),
		ProhibitOverlap: getBoolFlag(cmd, "prohibit-overlap", true),
		BinaryPath:      getStringFlag(cmd, "binary-path", NodeProbeInstalledPath),
		HistoryFile:     getStringFlag(cmd, "history-file", ProbeScheduleDefaultHistoryFile),
		Pushgateway:     getStringFlag(cmd, "push-prometheus", ""),
		Jurisdiction:    getStringFlag(cmd, "jurisdiction", ""),
		CPU:             getIntFlag(cmd, "cpu", 200),
		Memory:          getIntFlag(cmd, "memory", 256),
	}

	skipCats, _ := cmd.Flags().GetString("skip-categories")
	params.ArgsHCL = renderProbeScheduleArgs(strings.TrimSpace(skipCats))

	hcl, err := renderProbeScheduleHCL(params)
	if err != nil {
		return fmt.Errorf("render HCL: %w", err)
	}

	if dryRun {
		fmt.Fprint(cmd.OutOrStdout(), hcl)
		return nil
	}

	nc := nomadClientFromCmd(cmd)
	jobJSON, err := nc.ParseHCL(cmd.Context(), hcl)
	if err != nil {
		return fmt.Errorf("nomad HCL parse for %q: %w", ProbeScheduleJobID, err)
	}
	if _, err := nc.RegisterJob(cmd.Context(), jobJSON); err != nil {
		return fmt.Errorf("registering periodic probe job: %w", err)
	}

	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Registered periodic probe %q\n", ProbeScheduleJobID)
	fmt.Fprintf(out, "  schedule       %s (%s)\n", params.Cron, params.TimeZone)
	fmt.Fprintf(out, "  namespace      %s\n", params.Namespace)
	fmt.Fprintf(out, "  binary         %s\n", params.BinaryPath)
	fmt.Fprintf(out, "  history-file   %s\n", params.HistoryFile)
	if params.Pushgateway != "" {
		fmt.Fprintf(out, "  pushgateway    %s\n", params.Pushgateway)
	} else {
		fmt.Fprintf(out, "  pushgateway    (disabled)\n")
	}
	if params.Jurisdiction != "" {
		fmt.Fprintf(out, "  jurisdiction   %s\n", params.Jurisdiction)
	}
	return nil
}

// renderProbeScheduleHCL produces the HCL body. Pure function for tests.
func renderProbeScheduleHCL(p probeScheduleParams) (string, error) {
	var buf bytes.Buffer
	if err := probeScheduleTemplate.Execute(&buf, p); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// renderProbeScheduleArgs builds the HCL list literal for the probe args
// passed to abc-node-probe under raw_exec. The first three arguments are
// the same idempotent set used by every periodic invocation; the latter
// reference NOMAD_META values so the HCL itself stays stable regardless
// of operator overrides.
func renderProbeScheduleArgs(skipCategories string) string {
	args := []string{
		`"--quiet"`,
		`"--evaluate"`,
		`"--nomad-mode"`,
		`"--mode=stdout"`,
		`"--jurisdiction=${NOMAD_META_jurisdiction}"`,
		`"--history-file=${NOMAD_META_history_file}"`,
		`"--push-prometheus=${NOMAD_META_pushgateway}"`,
		`"--timeout=2m"`,
	}
	if skipCategories != "" {
		args = append(args, fmt.Sprintf(`"--skip-categories=%s"`, skipCategories))
	}
	return "[" + strings.Join(args, ", ") + "]"
}

func getStringFlag(cmd *cobra.Command, name, fallback string) string {
	v, _ := cmd.Flags().GetString(name)
	if strings.TrimSpace(v) == "" {
		return fallback
	}
	return v
}

func getBoolFlag(cmd *cobra.Command, name string, fallback bool) bool {
	if !cmd.Flags().Changed(name) {
		return fallback
	}
	v, _ := cmd.Flags().GetBool(name)
	return v
}

func getIntFlag(cmd *cobra.Command, name string, fallback int) int {
	if !cmd.Flags().Changed(name) {
		return fallback
	}
	v, _ := cmd.Flags().GetInt(name)
	if v == 0 {
		return fallback
	}
	return v
}
